spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-ailsa-dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-ailsa-test